### ISSUE TITLE
Breaks controls of lf file manager

### ISSUE THREAD

**Issue by danielwerg** [Strophox/tetrs#4]
https://github.com/gokcehan/lf

1. Start tetrs
2. Quit
3. `lf`
4. Can't use any keys in lf, see bottom of lf in screenshot

Then I would be forced to kill that terminal window.

![2024-07-30_14-28-10](https://github.com/user-attachments/assets/178f735b-01fe-4eb2-999f-a67ca885e67a)

Doesn't happens in [yazi](https://github.com/sxyazi/yazi)

**Comment by Strophox** [comment]
I've seen similar happen but only if the app `panic!`ed - I have a suspicion on how this might be solved, although I will write it down and debug at a later point in time (see note at top of readme). Thanks for the issue!

**Comment by Strophox** [comment]
The newest release tried improving the cmd line breakage situation. Let me know if it's better now! (Otherwise please describe more specifically the issue)

**Comment by danielwerg** [comment]
Fixed!
