### ISSUE TITLE
Piece rotation stops DAS / ARR

### ISSUE THREAD

**Issue by octopuserectus** [Strophox/tetrs#7]
Can be reproduced by holding a direction and rotating a piece mid ARR. 
Repeat will stop when the piece is rotated.

**Comment by Strophox** [comment]
This is an issue stemming from common terminal limitations (see ['Important note' in README](https://github.com/Strophox/tetrs/blob/main/README.md#how-to-run)).

To give further explanation:
Unless you use a terminal like [kitty](<https://sw.kovidgoyal.net/kitty/>) (or any terminal with [support for progressive keyboard enhancement](https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html)) I cannot read which buttons are being *held*, and instead have to rely on your terminal/OS/keyboard/whatever to send me the keypresses (where in this case it seems will only send me the most recent one).
